### ISSUE TITLE
ADS1299 Device 

### ISSUE THREAD

**Issue by rahulr2u** [topic-embedded-products/kernel-module-ads129x#1]
HI ,

While opening the device that is ads_cdev_open() func . I am exiting with ENODEV ,that is bad chip ID not an ads1298 chip. When I tried to read ads->chip[0].rx_buff[2] I am receiving 0x00 and then some arbitrary values . I doubt whether it is able to send and reive any data .I want to know what device tree entries should I include to make it work ?. I am using 3 chips of ADS1299 with in dasiy chain mode that is it will have same chip select . Is my dts entry correct ? :-
 
&spi3{
        #address-cells = <1>;
         #size-cells = <0>;
         ti,spi-num-cs = <1>;
         ti,hwmods = "spi3";
         ti,pindir-d0-out-d1-in;
         pinctrl-names = "default", "sleep";
         pinctrl-0 = <&spi3_default>;
         status = "okay"; 
        cs-gpios = <&gpio4 16 2>,<&gpio4 16 2>,<&gpio4 16 2>,<0>;
         bus-num = <3>;
         num-cs = <4>;
 
         ads129x@0 {
                 compatible = "ti,ads129x";
                 spi-max-frequency = <40000000>;
                 reg = <0>; /*chip select 0 */
                 dmas = <&edma 16
                     &edma 17>;
                 dma-names = "tx", "rx";
                 clksel-gpio = <&gpio4 10 0x07>; /*GPIO_3_0*/
                 reset-gpio = <&gpio4 11 0x07>;/*GPIO_3_1*/
                 start-gpio = <&gpio4 9 0x07>;/*GPIO_3_2*/
                 drdy-gpio = <&gpio4 19 0x07>;
 
               rdy-irq{
 
                     interrupts = <0 81 1 >; /* <convention , 113-32 , rising-edge>*/
                     interrupt-parent = <&gic>;
 
                };
         };
  ads129x@0{

    }

 ads129x@0{

    }

Thanks
Rahul

**Comment by MikeLooijmans** [comment]
﻿The driver has only been tested with ADS1298 devices. It only allows one to 
configure the device, the data capture doesn't actually work, we put that part 
into the FPGA. The driver also assumes that each has its own chipselect, 
daisy-chain wasn't implemented.

Because it's such a limited driver, I never bothered to submit it for mainline 
inclusion.

On 07-05-15 10:41, rahulr2u wrote:
> HI ,
>
> While opening the device that is ads_cdev_open() func . I am exiting with
> ENODEV ,that is bad chip ID not an ads1298 chip. When I tried to read
> ads->chip[0].rx_buff[2] I am receiving 0x00 and then some arbitrary values . I
> doubt whether it is able to send and reive any data .I want to know what
> device tree entries should I include to make it work ?. I am using 3 chips of
> ADS1299 with in dasiy chain mode that is it will have same chip select . Is my
> dts entry correct ? :-



Kind regards,

Mike Looijmans
System Expert

TOPIC Embedded Products
Eindhovenseweg 32-C, NL-5683 KH Best
Postbus 440, NL-5680 AK Best
Telefoon: +31 (0) 499 33 69 79
Telefax: +31 (0) 499 33 69 70
E-mail: mike.looijmans@topicproducts.com
Website: www.topicproducts.com

Please consider the environment before printing this e-mail
